package com.philipjhamilton.problem;

/**
 *
 Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

 By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 https://projecteuler.net/problem=2
 */
public class Problem2 implements Problem<Long>{

    @Override
    public Long solve() {
        long[] prev = new long[]{1, 2};
        long sum = 2;
        long temp = 0;

        while(sum <= 4_000_000){
            temp = prev[0] + prev[1];
            if(temp % 2 == 0){
                sum += temp;
            }
            prev[0] = prev[1];
            prev[1] = temp;
        }

        return sum;
    }

}
